title: "CC Translate:一款便捷的翻译工具"
url: "https://cctranslate.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://cctranslate.github.io/"
footer_text: "Page design by 业余时间"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "介绍"
    link: "/#introduce"
  - name: "如何使用"
    link: "/#howto"
  - name: "下载"
    link: "/#download"
  - name: "安装"
    link: "/#install"